apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "diagnosis"
  labels: 
    app: "diagnosis"
spec: 
  selector: 
    matchLabels: 
      app: "diagnosis"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "diagnosis"
    spec: 
      containers: 
        - 
          name: "diagnosis"
          image: "user04.azurecr.io/diagnosis:latest"
          ports: 
            - 
              containerPort: 80