apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnosis
  labels:
    app: diagnosis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnosis
  template:
    metadata:
      labels:
        app: diagnosis
    spec:
      containers:
        - name: diagnosis
          image: "user04.azurecr.io/diagnosis:latest"
          ports:
             - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
          env:
              - name: ORDER_LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                      name: config-dev
                      key: ORDER_LOG_LEVEL                
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8080
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 5
